spring.application.name=HCM-KS24-CNTT1_DuongGiaHuy_BusTicketPro
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/bus_ticket_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=huy0965507655
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# C?U HÌNH G?I EMAIL T? ??NG
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dgiahuy2911@gmail.com
spring.mail.password=nkep jbqn bwew cxoy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true